config/routes.rb
ApiAuth::Engine.routes.draw do
  resources :clients
  resources :requests
  resources :apis
  resources :clients do
    member do
      get :apis
      put :toggle_api
    end
  end

  root to: 'clients#index'
end

app/models/api_auth/api.rb
# frozen_string_literal: true

class ApiAuth::Api < ApplicationRecord
  has_many :requests
  has_and_belongs_to_many :clients
  validates :path, presence: true

  def allowed_methods
    allowed_request_methods = []
    allowed_request_methods << 'GET' if GET?
    allowed_request_methods << 'POST' if POST?
    allowed_request_methods << 'PUT' if PUT?
    allowed_request_methods << 'DELETE' if DELETE?
    allowed_request_methods
  end
end

app/models/api_auth/application_record.rb
module ApiAuth
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/api_auth/authorized_api.rb
# frozen_string_literal: true

module ApiAuth
  ##
  # client's authorized apis
  class AuthorizedApi < ApplicationRecord
    has_many :requests
    validates_presence_of :api, :client
    validates :api, uniqueness: { scope: :client_id }

    belongs_to :client
    belongs_to :api
    delegate :path, to: :api

    ##
    # path /users
    # path /users/:id
    def allow_request?(request)
      path_regx = path.gsub(':id', '\w+')
      request.path.match(/#{path_regx}/).present? && public_send("#{request.method}?")
    end
  end
end

app/models/api_auth/client.rb
# frozen_string_literal: true

module ApiAuth
  ##
  # Third apart information
  # Third aprt apply api by email
  # developers or operators manage clients information
  class Client < ApplicationRecord
    validates_presence_of :name, :email, :desc
    has_many :authorized_apis
    has_secure_token
    enum status: %i[active, disabled]

    ##
    def allow_request?(request)
      authorized_apis.find do |authorized_api|
        authorized_api.allow_request?(request)
      end.present?
    end

    def toggle_api(api, toggle_methods)
      toggle_methods.slice!(*api.allowed_methods)
      if (authorized_api = authorized_apis.find_by(api_id: api.id))
        authorized_api.update(toggle_methods)
      else
        authorized_apis.create(toggle_methods.merge(api_id: api.id))
      end
    end
  end
end

app/models/api_auth/request.rb
module ApiAuth
  class Request < ApplicationRecord
    belongs_to :authorized_api
  end
end

app/controllers/api_auth/apis_controller.rb
require_dependency "api_auth/application_controller"

module ApiAuth
  class ApisController < ApplicationController
    before_action :set_api, only: [:show, :edit, :update, :destroy]

    # GET /apis
    def index
      @apis = Api.all
    end

    # GET /apis/1
    def show
    end

    # GET /apis/new
    def new
      @api = Api.new
    end

    # GET /apis/1/edit
    def edit
    end

    # POST /apis
    def create
      @api = Api.new(api_params)

      if @api.save
        redirect_to @api, notice: 'Api was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /apis/1
    def update
      if @api.update(api_params)
        redirect_to apis_url, notice: 'Api was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /apis/1
    def destroy
      @api.destroy
      redirect_to apis_url, notice: 'Api was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_api
        @api = Api.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def api_params
        params.require(:api).permit(:path, :GET, :POST, :PUT, :DELETE)
      end
  end
end

app/controllers/api_auth/application_controller.rb
module ApiAuth
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/api_auth/clients_controller.rb
# frozen_string_literal: true

require_dependency "api_auth/application_controller"

module ApiAuth
  class ClientsController < ApplicationController
    before_action :set_client, only: [:show, :edit, :update, :destroy, :apis, :toggle_api]

    # GET /clients
    def index
      @clients = Client.all
    end

    # GET /clients/1
    def show
    end

    # GET /clients/new
    def new
      @client = Client.new
    end

    # GET /clients/1/edit
    def edit
    end

    # GET /clients/1/apis
    def apis
    end

    # PUT /clients/1/toggle_api
    def toggle_api
      api = Api.find(params[:api][:id])
      if api
        @client.toggle_api(api, api_params.require('api'))
      else
        render json: { message: 'api not found!' }, status: 422
      end
    end

    # POST /clients
    def create
      @client = Client.new(client_params)
      if @client.save
        redirect_to @client, notice: 'Client was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /clients/1
    def update
      if @client.update(client_params)
        redirect_to @client, notice: 'Client was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /clients/1
    def destroy
      @client.destroy
      redirect_to clients_url, notice: 'Client was successfully destroyed.'
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def client_params
      params.require(:client).permit(:name, :email, :desc)
    end

    def api_params
      params.permit(api: %i[id GET PUT DELETE POST])
    end
  end
end

app/controllers/api_auth/requests_controller.rb
require_dependency "api_auth/application_controller"

module ApiAuth
  class RequestsController < ApplicationController
    before_action :set_request, only: [:show, :edit, :update, :destroy]

    # GET /requests
    def index
      @requests = Request.all
    end

    # GET /requests/1
    def show
    end

    # GET /requests/new
    def new
      @request = Request.new
    end

    # GET /requests/1/edit
    def edit
    end

    # POST /requests
    def create
      @request = Request.new(request_params)

      if @request.save
        redirect_to @request, notice: 'Request was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /requests/1
    def update
      if @request.update(request_params)
        redirect_to @request, notice: 'Request was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /requests/1
    def destroy
      @request.destroy
      redirect_to requests_url, notice: 'Request was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_request
        @request = Request.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def request_params
        params.require(:request).permit(:api_id, :api_id, :amount, :date)
      end
  end
end

app/helpers/api_auth/apis_helper.rb
module ApiAuth
  module ApisHelper
  end
end

app/helpers/api_auth/application_helper.rb
module ApiAuth
  module ApplicationHelper
  end
end

app/helpers/api_auth/clients_helper.rb
module ApiAuth
  module ClientsHelper
  end
end

app/helpers/api_auth/requests_helper.rb
module ApiAuth
  module RequestsHelper
  end
end

app/views/api_auth/apis/_form.html.erb
<%= form_with(model: api, local: true) do |form| %>
  <% if api.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(api.errors.count, "error") %> prohibited this api from being saved:</h2>

      <ul>
      <% api.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :path %>
    <%= form.text_field :path, id: :api_path %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/api_auth/apis/_modal.html.erb
<div class="modal" id="<%= api.new_record? ? 'new_api' : 'edit_api' %>" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          <%= api.new_record? ? t('raw.create') : t('raw.edit') %><%= ApiAuth::Api.model_name.human %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for api do |f| %>
          <div class="form-group">
            <label class="form-label">
              <%= ApiAuth::Api.human_attribute_name('path') %>
            </label>
            <%= f.text_field :path, class: 'form-control' %>
          </div>
          <fieldset>
            <div class="form-group">
              <div class="form-check form-check-inline">
                <%= f.check_box :GET, class: 'form-check-input' %>
                <label class="form-check-label">GET</label>
              </div>
              <div class="form-check form-check-inline">
                <%= f.check_box :POST, class: 'form-check-input' %>
                <label class="form-check-label">POST</label>
              </div>
              <div class="form-check form-check-inline">
                <%= f.check_box :PUT, class: 'form-check-input' %>
                <label class="form-check-label">PUT</label>
              </div>
              <div class="form-check form-check-inline">
                <%= f.check_box :DELETE, class: 'form-check-input' %>
                <label class="form-check-label">DELETE</label>
              </div>
            </div>
          </fieldset>
          <%= f.button class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/api_auth/apis/edit.html.erb
<h1>Editing Api</h1>

<%= render 'form', api: @api %>

<%= link_to 'Show', @api %> |
<%= link_to 'Back', apis_path %>

app/views/api_auth/apis/edit.js.erb
if($('#edit_api').length == 0) {
  $('body').append("<%= j(render('modal', api: @api)) %>");
} else {
  $('#edit_api').replaceWith("<%= j(render('modal', api: @api)) %>");
}
$('#edit_api').modal('show');

app/views/api_auth/apis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apis</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= ApiAuth::Api.human_attribute_name(:path) %></th>
      <th>GET</th>
      <th>POST</th>
      <th>PUT</th>
      <th>DELETE</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @apis.each do |api| %>
      <tr>
        <td><%= api.path %></td>
        <td><%= api.GET %></td>
        <td><%= api.POST %></td>
        <td><%= api.PUT %></td>
        <td><%= api.DELETE %></td>
        <td>
          <%= link_to '编辑', edit_api_path(api), remote: true %>
          <%= link_to '删除', api, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "#{t('raw.create')}#{ApiAuth::Api.model_name.human}", '#new_api', class: 'btn btn-primary', data: {toggle: 'modal', target: '#new_api'} %>

<%= render 'api_auth/apis/modal', api: ApiAuth::Api.new %>

app/views/api_auth/apis/new.html.erb
<h1>New Api</h1>

<%= render 'form', api: @api %>

<%= link_to 'Back', apis_path %>

app/views/api_auth/apis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Path:</strong>
  <%= @api.path %>
</p>

<%= link_to 'Edit', edit_api_path(@api) %> |
<%= link_to 'Back', apis_path %>

app/views/api_auth/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :client_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, id: :client_email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :desc %>
    <%= form.text_area :desc, id: :client_desc, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
    <%= link_to '返回', clients_path, class: 'btn btn-defaultn' %>
  </div>
<% end %>

app/views/api_auth/clients/apis.html.erb
<%= hidden_field_tag 'client_id', @client.id %>
<table class="table">
  <thead>
    <tr>
      <th>URL</th>
      <th>GET</th>
      <th>POST</th>
      <th>PUT</th>
      <th>DELETE</th>
    </tr>
  </thead>
  <tbody>
    <% ApiAuth::Api.all.each do |api| %>
      <% authorized_api = @client.authorized_apis.find_by(api_id: api.id) %>
      <tr>
        <td>
          <%= api.path %>
          <%= hidden_field_tag 'api_id', api.id %>
        </td>
        <td>
          <div class="form-check">
            <%= check_box_tag 'GET', 'true', authorized_api.try(:GET), class: 'form-check-input toggle_api', disabled: !api.GET %>
          </div>
        </td>
        <td>
          <div class="form-check">
            <%= check_box_tag 'POST', 'true', authorized_api.try(:POST), class: 'form-check-input toggle_api', disabled: !api.POST %>
          </div>
        </td>
        <td>
          <div class="form-check">
            <%= check_box_tag 'PUT', 'true', authorized_api.try(:PUT), class: 'form-check-input toggle_api', disabled: !api.PUT %>
          </div>
        </td>
        <td>
          <div class="form-check">
            <%= check_box_tag 'DELETE', 'true', authorized_api.try(:DELETE), class: 'form-check-input toggle_api', disabled: !api.DELETE %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="actions">
  <%= link_to '返回', clients_path, class: 'btn btn-defaultn' %>
</div>

<script>
 $('.toggle_api').click(function(e){
   console.log('test');
   var api_id = e.target.parentElement.parentElement.parentElement.firstElementChild.lastElementChild.value;
   var params = {
     api: {
       id: api_id
     }
   };
   params['api'][e.target.name] = e.target.checked;
   var client_id = $('#client_id').val();
   var path = '/api_auth/clients/' + client_id + '/toggle_api';
   $.ajax(path, {
     method: 'PUT',
     data: params,
     dataType: 'json'
   })
 })
</script>

app/views/api_auth/clients/edit.html.erb
<h1>编辑客户</h1>

<%= render 'form', client: @client %>

app/views/api_auth/clients/index.html.erb
<h1>客户</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Desc</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.email %></td>
        <td><%= client.desc %></td>
        <td>
          <%= link_to '编辑', edit_client_path(client) %>
          <%= link_to '授权', apis_client_path(client) %>
          <%= link_to '删除', client, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '新建客户', new_client_path %>

app/views/api_auth/clients/new.html.erb
<h1>新建客户</h1>

<%= render 'form', client: @client %>

app/views/api_auth/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @client.desc %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/api_auth/requests/_form.html.erb
<%= form_with(model: request, local: true) do |form| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :api_id %>
    <%= form.number_field :api_id, id: :request_api_id %>
  </div>

  <div class="field">
    <%= form.label :api_id %>
    <%= form.number_field :api_id, id: :request_api_id %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, id: :request_amount %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :request_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/api_auth/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/api_auth/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th>Api</th>
      <th>Api</th>
      <th>Amount</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.api_id %></td>
        <td><%= request.api_id %></td>
        <td><%= request.amount %></td>
        <td><%= request.date %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/api_auth/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/api_auth/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Api:</strong>
  <%= @request.api_id %>
</p>

<p>
  <strong>Api:</strong>
  <%= @request.api_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @request.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @request.date %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>

app/views/layouts/api_auth/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Api auth</title>
    <%= stylesheet_link_tag    "api_auth/application", media: "all" %>
    <%= javascript_include_tag "api_auth/application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar sticky-top navbar-light navbar-expand-lg bg-light">
      <span class="navbar-brand">ApiAuth</span>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav">
          <li class="nav-item <%= 'active' if controller_name == 'clients'%>">
            <%= link_to '客户', api_auth.clients_path, class: 'nav-link' %>
          </li>
          <li class="nav-item <%= 'active' if controller_name == 'apis' %>">
            <%= link_to 'API', api_auth.apis_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container-fluid mb-5">
      <%= yield %>
    </div>
    <footer class="bd-footer bg-light fixed-bottom">
      <div class="float-right">
        ApiAuth V0.0.1
      </div>
    </footer>
  </body>
</html>